### ISSUE TITLE
FF Sync doesn't work with this extension / extension not published in addon store

### ISSUE THREAD

**Issue by MikeD23** [yannleretaille/firefox-addon-webrtcindicatorremover#1]
Is there any way how to force FF to sync this addon?
Maybe with setting the right domain in "services.sync.addons.trustedSourceHostnames"?

**Comment by yannleretaille** [comment]
I suppose for that it would need to be published officially as an FF addon. Do you have a certain application you need this for?

**Comment by MikeD23** [comment]
I need it for taking a new profile picture with external or builtin webcam. It's for a kiosk device on exhibitions. So I don't want this annoying overlay to show up. I also changed some configurations for durable webcam access and hiding info message for full screen mode. These settings can also be synced. 
For easiest configuration on new devices it would be nice to just let Firefox let sync all needed settings/addons. 
I was just looking for a way to force sync for non official addons. BTW thank you very much for your addon! This was the last thing to make my website look like I want in Firefox. Otherwise I probably would have to change the browser.

**Comment by yannleretaille** [comment]
Im glad the add-on helped you! I had the same issue with an kiosk application and was surprised that there was no option for the overlay in about:config. 
I changed the add-on name and published it as official add-on:
https://addons.mozilla.org/en-US/firefox/addon/disable-webrtc-overlay/
You'll have to delete the old version and install it again, but this should help with your sync issue.
Please tell me if this solved your problem!

**Comment by MikeD23** [comment]
Thank you very much! Monday on work I will have a look at it.

**Comment by yannleretaille** [comment]
@MikeD23 Hey, did you already check if everything works now?

**Comment by MikeD23** [comment]
Last time on Monday I checked your new addon officially uploaded it doesn't worked correctly. The overlay wasn't hiding with it. After install of your old addon version it worked again. 
Did you change something in the code?

**Comment by yannleretaille** [comment]
Looks like I might have introduced a new bug when I cleaned up the code before releasing it officially.
I think I fixed it now, can you try out the [new version](https://addons.mozilla.org/en-US/firefox/addon/disable-webrtc-overlay/) ?

**Comment by MikeD23** [comment]
Right now I'm on vacation. I can try the new version not before 4th of July.

**Comment by yannleretaille** [comment]
Hi Mike, is everything ok now (except maybe #2)? I'd like to close this issue.

**Comment by MikeD23** [comment]
Yes, it work's again. Thank you!
